defmodule NombreTest do
  use ExUnit.Case

  def expect_words(n, w), do: assert Nombre.number_to_words(n) == w

  test ":number_to_words should return the equivalent English word of a integer" do
    expect_words 0, "zero"
    expect_words 1, "one"
    expect_words 2, "two"
    expect_words 10, "ten"
    expect_words 12, "twelve"
    expect_words 18, "eighteen"
    expect_words 20, "twenty"
    expect_words 21, "twenty one"
    expect_words 22, "twenty two"
    expect_words 31, "thirty one"
    expect_words 33, "thirty three"
    expect_words 44, "forty four"
    expect_words 55, "fifty five"
    expect_words 66, "sixty six"
    expect_words 70, "seventy"
    expect_words 71, "seventy one"
    expect_words 72, "seventy two"
    expect_words 80, "eighty"
    expect_words 81, "eighty one"
    expect_words 90, "ninety"
    expect_words 99, "ninety nine"
    expect_words 100, "one hundred"
    expect_words 101, "one hundred one"
    expect_words 110, "one hundred ten"
    expect_words 111, "one hundred eleven"
    expect_words 119, "one hundred nineteen"
    expect_words 120, "one hundred twenty"
    expect_words 185, "one hundred eighty five"
    expect_words 300, "three hundred"
    expect_words 301, "three hundred one"
    expect_words 999, "nine hundred ninety nine"
    expect_words 1000, "one thousand"
    expect_words 1001, "one thousand one"
    expect_words 1002, "one thousand two"
    expect_words 1095, "one thousand ninety five"
    expect_words 1102, "one thousand one hundred two"
    expect_words 1199, "one thousand one hundred ninety nine"
    expect_words 1234, "one thousand two hundred thirty four"
    expect_words 2001, "two thousand one"
    expect_words 12001, "twelve thousand one"
    expect_words 12345, "twelve thousand three hundred forty five"
    expect_words 12500, "twelve thousand five hundred"
    expect_words 123456, "one hundred twenty three thousand four hundred fifty six"
    expect_words 1234567, "one million two hundred thirty four thousand five hundred sixty seven"
    expect_words 9999999, "nine million nine hundred ninety nine thousand nine hundred ninety nine"
    expect_words 12345678, "twelve million three hundred forty five thousand six hundred seventy eight"
    expect_words 999999999, "nine hundred ninety nine million nine hundred ninety nine thousand nine hundred ninety nine"
    expect_words 999999999999, "nine hundred ninety nine billion nine hundred ninety nine million nine hundred ninety nine thousand nine hundred ninety nine"
  end
end
